- name: create maddy group
  group:
    name: "{{ maddy_user }}"
    state: present

- name: create maddy user
  user:
    name: "{{ maddy_user }}"
    group: "{{ maddy_user }}"
    createhome: true

- name: create needed dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ maddy_user }}"
  with_items:
    - /etc/maddy
    - /var/lib/maddy
    - /run/maddy

- name: install zstd
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ["zstd", "unzip"]

- name: fetch maddy
  get_url:
    url: "{{ maddy_url }}"
    dest: "{{ maddy_user_dir }}/maddy.tar.zst"
  register: fetch

- name: uncompress maddy
  shell: |
    cd "{{ maddy_user_dir }}"
    rm -rf maddy
    tar -I zstd -xf maddy.tar.zst
    mv maddy*musl maddy
  when: fetch.changed

- name: install maddy binaries
  copy:
    src: "{{ maddy_user_dir }}/maddy/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    mode: 0755
    remote_src: true
  with_items: ["maddy", "maddyctl"]

- name: maddy conf file
  template: src=maddy.conf.j2 dest=/etc/maddy/maddy.conf
  notify:
    - restart maddy

- name: maddy service file
  template: src=maddy.service.j2 dest=/etc/systemd/system/maddy.service
  notify:
    - reload systemd maddy
    - restart maddy

- name: start/enable maddy
  service: name=maddy state=started enabled=yes
